In [7]:
import torch

# 示例：条件替换
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([10, 20, 30, 40])
cond = torch.tensor([True, False, True, False])

# 满足 cond=True 时取 a，否则取 b
out = torch.where(cond, a, b)
print(out)  # 输出: tensor([ 1, 20,  3, 40])

tensor([ 1, 20,  3, 40])


In [8]:
# 示例：外积计算
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 外积结果：每个元素是 a[i] * b[j]
outer_result = torch.outer(a, b)
print(outer_result)
# 输出:
# tensor([[ 4,  5,  6],
#         [ 8, 10, 12],
#         [12, 15, 18]])

tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])


In [9]:
# 示例：拼接操作
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])

# 沿第0维（行）拼接
cat_dim0 = torch.cat([t1, t2], dim=0)
print(cat_dim0)
# 输出:
# tensor([[1, 2],
#         [3, 4],
#         [5, 6],
#         [7, 8]])

# 沿第1维（列）拼接
cat_dim1 = torch.cat([t1, t2], dim=1)
print(cat_dim1)
# 输出:
# tensor([[1, 2, 5, 6],
#         [3, 4, 7, 8]])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [10]:
# 示例：增加维度
t1 = torch.Tensor([1, 2, 3])

# 在第0维增加维度（形状从 (3,) → (1,3)）
t2 = t1.unsqueeze(0)
print(t2.shape)  # 输出: torch.Size([1, 3])

# 在最后一维增加维度（形状从 (3,) → (3,1)）
t3 = t1.unsqueeze(-1)
print(t3.shape)  # 输出: torch.Size([3, 1])

torch.Size([1, 3])
torch.Size([3, 1])


In [11]:
# 示例：数值约束
x = torch.tensor([1.0, 2.0, 3.0, 4.0])

# 将元素限制在 [2, 3] 之间
clamped = torch.clamp(x, min=2, max=3)
print(clamped)  # 输出: tensor([2., 2., 3., 3.])

# 仅设置下界（负数保留）
clamped_min = torch.clamp(x, min=0)
print(clamped_min)  # 输出: tensor([1., 2., 3., 4.])

# 仅设置上界
clamped_max = torch.clamp(x, max=2)
print(clamped_max)  # 输出: tensor([1., 2., 2., 2.])

tensor([2., 2., 3., 3.])
tensor([1., 2., 3., 4.])
tensor([1., 2., 2., 2.])


In [12]:
import torch
import torch.nn as nn

# 定义 Dropout 层（p=0.5 表示训练时随机丢弃50%的神经元）
dropout = nn.Dropout(p=0.5)

# 输入数据（模拟全连接层输出）
input_data = torch.randn(1, 10)  # 形状 (batch_size=1, 特征数=10)

# 训练模式：启用 Dropout
dropout.train()
output_train = dropout(input_data)
print("训练模式输出（部分神经元被置零）:\n", output_train)

# 测试模式：禁用 Dropout
dropout.eval()
output_eval = dropout(input_data)
print("测试模式输出（无神经元被置零）:\n", output_eval)

训练模式输出（部分神经元被置零）:
 tensor([[-0.0000, -0.0000,  0.2750, -0.0000, -0.0000,  2.0247, -0.0000, -3.3719,
          0.0000, -2.2431]])
测试模式输出（无神经元被置零）:
 tensor([[-0.1942, -1.7351,  0.1375, -1.3931, -1.0972,  1.0124, -0.3694, -1.6860,
          0.7677, -1.1216]])


In [15]:
import torch
import torch.nn as nn

class LinearDemo(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(in_features=input_size, out_features=output_size,bias= True)

    def forward(self, x):
        return self.linear(x)

if __name__ == "__main__":
    # 初始化线性层：输入特征数2，输出特征数3
    model = LinearDemo(2, 3)
    # 生成测试输入：批量大小4，输入特征2
    input_data = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], dtype=torch.float32)
    # 前向传播
    output = model(input_data)
    # 输出结果信息
    print("输入张量形状:", input_data.shape)
    print("输出张量形状:", output.shape)
    print("输入张量:\n", input_data)
    print("输出张量:\n", output)
    # 查看线性层参数
    print("权重矩阵:\n", model.linear.weight)
    print("偏置向量:\n", model.linear.bias)


输入张量形状: torch.Size([4, 2])
输出张量形状: torch.Size([4, 3])
输入张量:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
输出张量:
 tensor([[ 0.4216, -1.4816, -0.5201],
        [ 0.4281, -3.1054, -0.4448],
        [ 0.4345, -4.7292, -0.3696],
        [ 0.4410, -6.3530, -0.2943]], grad_fn=<MmBackward0>)
权重矩阵:
 Parameter containing:
tensor([[-0.4152,  0.4184],
        [-0.1422, -0.6697],
        [ 0.5953, -0.5577]], requires_grad=True)
偏置向量:
 None


In [17]:
import torch

def torch_view_demo():
    # 示例1：一维张量转二维（2行3列）
    x1 = torch.tensor([1, 2, 3, 4, 5, 6])
    print("原始一维张量:", x1)
    x1_view = x1.view(2, 3)
    print("view(2,3)后形状:", x1_view.shape)
    print("view(2,3)后张量:\n", x1_view)

    # 示例2：二维张量转三维（3×2×1）
    x2 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 2×3
    x2_view = x2.view(3, 2, 1)
    print("\n原始二维张量:\n", x2)
    print("view(3,2,1)后形状:", x2_view.shape)
    print("view(3,2,1)后张量:\n", x2_view)

    # 示例3：用-1自动计算维度（6元素→3×2）
    x3 = torch.tensor([1, 2, 3, 4, 5, 6])
    x3_view = x3.view(-1, 2)  # 第一维自动算为3（6/2）
    print("\n原始一维张量:", x3)
    print("view(-1,2)后形状:", x3_view.shape)
    print("view(-1,2)后张量:\n", x3_view)

    # 示例4：非连续张量需先contiguous()
    x4 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 2×3
    x4_t = x4.transpose(0, 1)  # 转置为3×2（非连续）
    print("\n转置后的非连续张量:\n", x4_t)
    try:
        x4_t_view = x4_t.view(6)  # 直接view会报错
    except RuntimeError as e:
        print("直接view非连续张量的错误:", e)
    # 正确做法：先contiguous()再view()
    x4_t_contig = x4_t.contiguous()
    x4_t_view = x4_t_contig.view(6)
    print("contiguous()后view(6)的形状:", x4_t_view.shape)
    print("contiguous()后view(6)的张量:", x4_t_view)

if __name__ == "__main__":
    torch_view_demo()


原始一维张量: tensor([1, 2, 3, 4, 5, 6])
view(2,3)后形状: torch.Size([2, 3])
view(2,3)后张量:
 tensor([[1, 2, 3],
        [4, 5, 6]])

原始二维张量:
 tensor([[1, 2, 3],
        [4, 5, 6]])
view(3,2,1)后形状: torch.Size([3, 2, 1])
view(3,2,1)后张量:
 tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

原始一维张量: tensor([1, 2, 3, 4, 5, 6])
view(-1,2)后形状: torch.Size([3, 2])
view(-1,2)后张量:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

转置后的非连续张量:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
直接view非连续张量的错误: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
contiguous()后view(6)的形状: torch.Size([6])
contiguous()后view(6)的张量: tensor([1, 4, 2, 5, 3, 6])


In [18]:
import torch

def torch_transpose_demo():
    # 示例1：2D张量转置（交换dim0和dim1）
    x1 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 形状(2,3)
    print("原始2D张量:\n", x1)
    print("原始形状:", x1.shape)
    x1_t = torch.transpose(x1, 0, 1)  # 交换第0和第1维
    print("transpose(0,1)后形状:", x1_t.shape)
    print("transpose(0,1)后张量:\n", x1_t)

    # 示例2：3D张量交换dim1和dim2（形状(batch, channel, height)→(batch, height, channel)）
    x2 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 形状(2,2,2)
    print("\n原始3D张量:\n", x2)
    print("原始形状:", x2.shape)
    x2_t = torch.transpose(x2, 1, 2)  # 交换第1和第2维
    print("transpose(1,2)后形状:", x2_t.shape)
    print("transpose(1,2)后张量:\n", x2_t)

    # 示例3：非连续张量的处理（transpose后是non-contiguous，view需先contiguous）
    x3 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # (2,3)
    x3_t = torch.transpose(x3, 0, 1)  # (3,2)，非连续
    print("\n转置后的非连续张量:\n", x3_t)
    print("转置后形状:", x3_t.shape)
    print("是否连续:", x3_t.is_contiguous())
    try:
        x3_t_view = x3_t.view(6)  # 直接view报错
    except RuntimeError as e:
        print("直接view非连续张量的错误:", e)
    # 正确做法：先contiguous再view
    x3_t_contig = x3_t.contiguous()
    x3_t_view = x3_t_contig.view(6)
    print("contiguous()后view(6)的形状:", x3_t_view.shape)
    print("contiguous()后view(6)的张量:", x3_t_view)

    # 示例4：错误情况（指定不存在的维度）
    try:
        x4 = torch.tensor([1, 2, 3])
        x4_t = torch.transpose(x4, 0, 2)  # x4是1D，只有dim0，指定dim2报错
    except IndexError as e:
        print("\n指定不存在维度的错误:", e)

if __name__ == "__main__":
    torch_transpose_demo()


原始2D张量:
 tensor([[1, 2, 3],
        [4, 5, 6]])
原始形状: torch.Size([2, 3])
transpose(0,1)后形状: torch.Size([3, 2])
transpose(0,1)后张量:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])

原始3D张量:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
原始形状: torch.Size([2, 2, 2])
transpose(1,2)后形状: torch.Size([2, 2, 2])
transpose(1,2)后张量:
 tensor([[[1, 3],
         [2, 4]],

        [[5, 7],
         [6, 8]]])

转置后的非连续张量:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
转置后形状: torch.Size([3, 2])
是否连续: False
直接view非连续张量的错误: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
contiguous()后view(6)的形状: torch.Size([6])
contiguous()后view(6)的张量: tensor([1, 4, 2, 5, 3, 6])

指定不存在维度的错误: Dimension out of range (expected to be in range of [-1, 0], but got 2)


In [19]:
import torch

def torch_triu_demo():
    # 示例1：基本用法（2D张量，默认diagonal=0，保留主对角线及以上元素）
    x1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
    print("原2D张量:\n", x1)
    triu_default = torch.triu(x1)
    print("triu(默认diagonal=0)结果:\n", triu_default)

    # 示例2：调整diagonal参数（diagonal=1，保留主对角线以上1行的元素）
    triu_diag1 = torch.triu(x1, diagonal=1)
    print("\ntriu(diagonal=1)结果:\n", triu_diag1)

    # 示例3：diagonal=-1（保留主对角线以下1行及以上的元素）
    triu_diag_neg1 = torch.triu(x1, diagonal=-1)
    print("\ntriu(diagonal=-1)结果:\n", triu_diag_neg1)

    # 示例4：高维张量（3D张量，对每个2D切片应用triu）
    x2 = torch.stack([x1, x1 * 2])  # 形状(2, 3, 3)
    print("\n原3D张量形状:", x2.shape)
    triu_3d = torch.triu(x2, diagonal=0)
    print("3D张量triu后形状:", triu_3d.shape)
    print("3D张量triu后第一个切片:\n", triu_3d[0])

    # 示例5：非连续张量处理（转置后应用triu）
    x3 = x1.transpose(0, 1)  # 转置为(3,3)，非连续张量
    print("\n转置后张量形状:", x3.shape)
    print("转置后是否连续:", x3.is_contiguous())
    triu_non_contig = torch.triu(x3, diagonal=0)
    print("非连续张量triu结果:\n", triu_non_contig)

if __name__ == "__main__":
    torch_triu_demo()

原2D张量:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
triu(默认diagonal=0)结果:
 tensor([[1., 2., 3.],
        [0., 5., 6.],
        [0., 0., 9.]])

triu(diagonal=1)结果:
 tensor([[0., 2., 3.],
        [0., 0., 6.],
        [0., 0., 0.]])

triu(diagonal=-1)结果:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 8., 9.]])

原3D张量形状: torch.Size([2, 3, 3])
3D张量triu后形状: torch.Size([2, 3, 3])
3D张量triu后第一个切片:
 tensor([[1., 2., 3.],
        [0., 5., 6.],
        [0., 0., 9.]])

转置后张量形状: torch.Size([3, 3])
转置后是否连续: False
非连续张量triu结果:
 tensor([[1., 4., 7.],
        [0., 5., 8.],
        [0., 0., 9.]])
